# SGLang Inference config for Qwen2.5-7B-Instruct.

model:
  model_name: "Qwen/Qwen2.5-7B-Instruct"
  model_max_length: 131072
  trust_remote_code: true

remote_params:
  api_url: "http://127.0.0.1:6864/generate"

engine: SGLANG

