# SGLang Inference config for Dans-PersonalityEngine-V1.2.0-24b.

model:
  model_name: "PocketDoc/Dans-PersonalityEngine-V1.2.0-24b"
  trust_remote_code: true

remote_params:
  api_url: "http://127.0.0.1:6864/generate"

engine: SGLANG

