model:
  model_name: "claude-3-5-sonnet-latest"
  model_max_length: 200000

inference_engine: ANTHROPIC

generation:
  temperature: 0.0

tasks:
  - evaluation_backend: custom
    task_name: berry_bench
