model:
  model_name: "gpt-4o"
  model_max_length: 128000

inference_engine: OPENAI

generation:
  max_new_tokens: 8192
  temperature: 0.0

tasks:
  - evaluation_backend: custom
    task_name: berry_bench
