model:
  model_name: "gpt-4o"
  is_vision_capable: true
  is_omni_capable: true

inference_engine: OPENAI

generation:
  max_new_tokens: 8192
  temperature: 0.0

tasks:
  - evaluation_backend: custom
    task_name: berry_bench
