# SGLang Inference config for Llama-3.3-70B-Instruct.

model:
  model_name: "meta-llama/Llama-3.3-70B-Instruct"
  model_max_length: 131072
  trust_remote_code: true

remote_params:
  api_url: "http://127.0.0.1:6864/generate"

engine: SGLANG

